org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.1)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1



mod_id=mewosgear
mod_name=Mewo's Gear
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.mewo.mewosgear
mod_authors=Mewo_cat
mod_description=A work in progress mod that should someday add gear and equipment.